/*
Copyright (c) 2017-2025 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module psx.ram;

enum PSX_RAM_SIZE = 2048 * 1024;
enum PSX_BIOS_SIZE = 512 * 1024;
enum PSX_BIOS_OFFSET_KSEG1 = 0xA0000000 - 0x1FC00000;

struct PsxRam
{
    ubyte[] data;

    void init(size_t size)
    {
        data = new ubyte[size];
    }

    uint read32(uint offset)
    {
        uint b0 = data[offset + 0];
        uint b1 = data[offset + 1];
        uint b2 = data[offset + 2];
        uint b3 = data[offset + 3];

        return b0 | (b1 << 8) | (b2 << 16) | (b3 << 24);
    }

    void write32(uint offset, uint val)
    {
        ubyte b0 = cast(ubyte)val;
        ubyte b1 = cast(ubyte)(val >> 8);
        ubyte b2 = cast(ubyte)(val >> 16);
        ubyte b3 = cast(ubyte)(val >> 24);

        data[offset + 0] = b0;
        data[offset + 1] = b1;
        data[offset + 2] = b2;
        data[offset + 3] = b3;
    }

    ushort read16(uint offset)
    {
        ushort b0 = cast(ushort)data[offset + 0];
        ushort b1 = cast(ushort)data[offset + 1];

        return cast(ushort)(b0 | (b1 << 8));
    }

    void write16(uint offset, ushort val)
    {
        ubyte b0 = cast(ubyte)val;
        ubyte b1 = cast(ubyte)(val >> 8);

        data[offset + 0] = b0;
        data[offset + 1] = b1;
    }

    void write8(uint offset, ubyte val)
    {
        data[offset] = val;
    }

    ubyte read8(uint offset)
    {
        return data[offset];
    }
}
