/*
Copyright (c) 2017-2025 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module main;

import core.thread;
import core.atomic;
import std.stdio;
import std.file;
import std.digest.sha;
import std.conv;
import std.string;
import std.math;

import bindbc.sdl;

import psx.cpu;
import psx.gpu;

/*
void gpuBlitFramebuffer(PsxGpu* gpu, ubyte[] buffer, uint bufferWidth, uint bufferHeight)
{
    foreach (y; 0..bufferHeight)
    {
        foreach (x; 0..bufferWidth)
        {
            ushort pix = gpu.vram[y * VRAM_WIDTH + x];
            
            int r = (pix      ) & 0x1F;
            int g = (pix >> 5 ) & 0x1F;
            int b = (pix >> 10) & 0x1F;

            r = (r << 3) | (r >> 2);
            g = (g << 3) | (g >> 2);
            b = (b << 3) | (b >> 2);

            int dstIndex = (y * bufferWidth + x) * 4;
            buffer[dstIndex + 0] = cast(ubyte)r; // R
            buffer[dstIndex + 1] = cast(ubyte)g; // G
            buffer[dstIndex + 2] = cast(ubyte)b; // B
            buffer[dstIndex + 3] = 255;          // A
        }
    }
}
*/

void main()
{
    SDLSupport sdlsup = loadSDL();
    if (sdlsup != sdlSupport)
    {
        if (sdlsup != SDLSupport.badLibrary)
        {
            writeln("Error: SDL library is not found. Please, install SDL 2.0.14");
            return;
        }
    }
    
    if (SDL_Init(SDL_INIT_EVERYTHING) == -1)
    {
        writeln("Error: failed to init SDL: ", to!string(SDL_GetError()));
        return;
    }
    
    enum videoWidth = VRAM_WIDTH;
    enum videoHeight = VRAM_HEIGHT;
    
    SDL_Window* window = SDL_CreateWindow(toStringz("Gecko's PlayStation Emulator"),
        SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED,
        videoWidth, videoHeight,
        SDL_WINDOW_SHOWN);
    if (window is null)
    {
        writeln("Error: failed to create window: ", to!string(SDL_GetError()));
        return;
    }
    
    SDL_Surface* windowSurface = SDL_GetWindowSurface(window);
    
    string biosFilename = "bios/SCPH1001.BIN";
    ubyte[] bios = cast(ubyte[])read(biosFilename);
    size_t biosSize = bios.length;
    ubyte[20] shaChecksum = sha1Of(bios);
    writefln("BIOS file: %s", biosFilename);
    writefln("Size: %s byte(s)", biosSize);
    writefln("SHA-1 hash: %s", toHexString(shaChecksum));
    
    PsxCpu cpu;
    cpu.init(bios);
    
    SDL_Surface* displaySurface = SDL_CreateRGBSurfaceFrom(
        cpu.gpu.vram.ptr, videoWidth, videoHeight, 32, videoWidth * 4,
        0x000000FF, 0x0000FF00, 0x00FF0000, 0);
    
    SDL_Event event;
    bool running = true;
    
    writeln("Running...");
    
    void cpuLoop()
    {
        while(atomicLoad(cpu.running))
        {
            cpu.runNextInstruction();
        }
    };
    
    Thread cpuThread = new Thread(&cpuLoop);
    cpuThread.start();
    
    enum FRAME_TIME_MS = 16;
    
    uint frameStart;
    uint frameEnd;
    uint elapsed;
    
    while(running)
    {
        bool shouldUpdateDisplay = atomicLoad(cpu.running);
        
        frameStart = SDL_GetTicks();
        
        while(SDL_PollEvent(&event))
        {
            if (event.type == SDL_QUIT)
            {
                cpu.stop();
                running = false;
            }
        }

        if (shouldUpdateDisplay)
        {
            if (atomicLoad(cpu.gpu.frameReady))
            {
                SDL_BlitSurface(displaySurface, null, windowSurface, null);
                
                atomicStore(cpu.gpu.frameReady, false);
                
                // Release VRAM for writing
                atomicStore(cpu.gpu.frameLocked, false);
                
                SDL_UpdateWindowSurface(window);
            }
        }
        
        frameEnd = SDL_GetTicks();
        elapsed = frameEnd - frameStart;

        if (elapsed < FRAME_TIME_MS)
        {
            SDL_Delay(FRAME_TIME_MS - elapsed);
        }
    }
    
    SDL_FreeSurface(displaySurface);
    SDL_Quit();
}
